---

resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook_url))

- name: alpine-image
  type: docker-image
  source:
    repository: alpine

- name: dockerfile
  type: git
  source:
    uri: https://github.com/resilientscale/docker-images.git
    branch: master
    username: ((github_username))
    password: ((github_password))
    paths: [alpine/Dockerfile]

- name: docker-image
  type: docker-image
  source:
    repository: rscale/alpine-base
    username: ((docker_hub_user))
    password: ((docker_hub_password))

jobs:

- name: prepare
  serial_groups: [release]
  plan:
  - in_parallel:
    - get: alpine-image
      trigger: true
    - get: dockerfile
      trigger: true
  - put: docker-image
    params:
      build: dockerfile/alpine
    on_success:
      put: slack
      params:
        username: "rscale-ci"
        text: "SUCCESS: New alpine-base image published to docker hub at rscale/alpine-base. (https://ci.aws.rscale.io/teams/docker-images/pipelines/alpine-base)"
    on_failure:
      put: slack
      params: 
        username: "rscale-ci"
        text: "FAILURE: Creation of new alpine-base image failed. (https://ci.aws.rscale.io/teams/docker-images/pipelines/alpine-base)"
