---

resource_types:

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook_url))

- name: base-image
  type: docker-image
  source:
    repository: rscale/ubuntu-jq

- name: dockerfile
  type: git
  source:
    uri: https://github.com/resilientscale/docker-images.git
    branch: master
    username: ((github_username))
    password: ((github_password))
    paths: [ubuntu-yq/Dockerfile]
  check_every: 60m

- name: tasks
  type: git
  source:
    uri: https://github.com/resilientscale/docker-images.git
    branch: master
    username: ((github_username))
    password: ((github_password))
    paths: [ubuntu-yq/tasks/*]
  check_every: 60m

- name: yq-release
  type: github-release
  source:
    owner: mikefarah
    repository: yq
    access_token: ((github_password))
  check_every: 60m

- name: docker-image
  type: docker-image
  source:
    repository: rscale/ubuntu-yq
    username: ((docker_hub_user))
    password: ((docker_hub_password))

jobs:
- name: build
  serial_groups: [release]
  plan:
  - in_parallel:
    - get: base-image
      trigger: true
    - get: dockerfile
      trigger: true
      params: {depth: 1}
    - get: yq-release
      trigger: true
    - get: tasks
      params: {depth: 1}
  - task: prepare-envars
    file: tasks/ubuntu-yq/tasks/prepare-envars.yml
  - put: docker-image
    params:
      build: dockerfile/ubuntu-yq
      build_args_file: envars/env.json
      labels_file: envars/env.json
      tag_file: tag_file/tag
      tag_as_latest: true
    on_success:
      put: slack
      params:
        username: "rscale-ci"
        text: "SUCCESS: New ubuntu-yq image published to docker hub at rscale/ubuntu-yq. (https://ci.aws.rscale.io/teams/docker-images/pipelines/ubuntu-yq)"
    on_failure:
      put: slack
      params: 
        username: "rscale-ci"
        text: "FAILURE: Creation of new ubuntu-yq image failed. (https://ci.aws.rscale.io/teams/docker-images/pipelines/ubuntu-yq)"
  
