---
resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource

resources:

- name: slack
  type: slack-notification
  source:
    url: ((slack_webhook_url))

- name: image-source
  type: git
  source:
    uri: https://github.com/resilientscale/docker-images.git
    branch: master
    username: ((github_username))
    password: ((github_password))
    paths: [((docker_file))]

- name: docker-image
  type: docker-image
  source:
    repository: rscale/((image_name))
    username: ((docker_hub_user))
    password: ((docker_hub_password))

jobs:
- name: build-image
  public: false
  plan:
  - get: image-source
    trigger: true
  - put: docker-image
    params:
      build: image-source/((docker_file))
    on_success:
      put: slack
      params:
        username: "rscale-ci"
        text: "SUCCESS: New ((image_name)) image published to docker hub at rscale/((image_name)). (https://ci.aws.rscale.io/teams/docker-images/pipelines/((image_name)))"
    on_failure:
      put: slack
      params: 
        username: "rscale-ci"
        text: "FAILURE: Creation of new ((image_name)) image failed. (https://ci.aws.rscale.io/teams/docker-images/pipelines/((image_name)))"
  
