FROM rscale/alpine-base

RUN apk add --update --no-cache \
  libgcc --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
  libstdc++ --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
  musl --repository=http://dl-cdn.alpinelinux.org/alpine/edge/main \
  hugo --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community

	
