---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/ubuntu-base
    tag: 'latest'

inputs:
- name: git-tag
- name: tasks

outputs:
- name: envars
- name: tag_file

run:
  path: tasks/ubuntu-with-github-release/tasks/prepare-envars.sh
